# Generated by Django 5.2.7 on 2025-10-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_resource_description_remove_resource_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
